version: "3.8"

services:

  greeter_service:
    image: greeter_service
    container_name: greeter_service
    hostname: greeter_service
    build:
      context: ./greeter-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      GREETER_SERVICE_ADDRESS: ${GREETER_SERVICE_ADDRESS}
    networks:
      - network

  reservation_service:
    image: reservation_service
    container_name: reservation_service
    hostname: reservation_service
    build:
      context: ./reservation-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      RESERVATION_SERVICE_ADDRESS: ${RESERVATION_SERVICE_ADDRESS}
    networks:
      - network

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment:
      GREETER_SERVICE_ADDRESS: greeter_service:8000
      RESERVATION_SERVICE_ADDRESS: reservation_service:8001
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
    depends_on:
      - greeter_service
      - reservation_service
    networks:
      - network
    ports:
      - "8000:8000"

networks:
  network:
    driver: bridge
